using System.Collections.Generic;
using System.Text.Json.Serialization;
using YTStdTenantPlatform.Application.Dtos;

namespace YTStdTenantPlatform.Infrastructure.Serialization;

[JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Metadata)]
[JsonSerializable(typeof(ApiResult))]
[JsonSerializable(typeof(ApiResult<PlatformUserDto>))]
[JsonSerializable(typeof(ApiResult<PlatformRoleDto>))]
[JsonSerializable(typeof(ApiResult<PlatformPermissionDto>))]
[JsonSerializable(typeof(ApiResult<TenantDto>))]
[JsonSerializable(typeof(ApiResult<TenantLifecycleEventDto>))]
[JsonSerializable(typeof(ApiResult<TenantGroupDto>))]
[JsonSerializable(typeof(ApiResult<TenantDomainDto>))]
[JsonSerializable(typeof(ApiResult<TenantTagDto>))]
[JsonSerializable(typeof(ApiResult<TenantResourceQuotaDto>))]
[JsonSerializable(typeof(ApiResult<TenantSystemConfigDto>))]
[JsonSerializable(typeof(ApiResult<TenantFeatureFlagDto>))]
[JsonSerializable(typeof(ApiResult<TenantParameterDto>))]
[JsonSerializable(typeof(ApiResult<SaasPackageDto>))]
[JsonSerializable(typeof(ApiResult<SaasPackageVersionDto>))]
[JsonSerializable(typeof(ApiResult<SaasPackageCapabilityDto>))]
[JsonSerializable(typeof(ApiResult<TenantSubscriptionDto>))]
[JsonSerializable(typeof(ApiResult<TenantTrialDto>))]
[JsonSerializable(typeof(ApiResult<TenantSubscriptionChangeDto>))]
[JsonSerializable(typeof(ApiResult<BillingInvoiceDto>))]
[JsonSerializable(typeof(ApiResult<BillingInvoiceItemDto>))]
[JsonSerializable(typeof(ApiResult<PaymentOrderDto>))]
[JsonSerializable(typeof(ApiResult<PaymentRefundDto>))]
[JsonSerializable(typeof(ApiResult<TenantApiKeyDto>))]
[JsonSerializable(typeof(ApiResult<ApiKeyCreatedResult>))]
[JsonSerializable(typeof(ApiResult<TenantApiUsageStatDto>))]
[JsonSerializable(typeof(ApiResult<WebhookEventDto>))]
[JsonSerializable(typeof(ApiResult<TenantWebhookDto>))]
[JsonSerializable(typeof(ApiResult<WebhookDeliveryLogDto>))]
[JsonSerializable(typeof(ApiResult<TenantDailyStatDto>))]
[JsonSerializable(typeof(ApiResult<PlatformMonitorMetricDto>))]
[JsonSerializable(typeof(ApiResult<OperationLogDto>))]
[JsonSerializable(typeof(ApiResult<AuditLogDto>))]
[JsonSerializable(typeof(ApiResult<SystemLogDto>))]
[JsonSerializable(typeof(ApiResult<NotificationTemplateDto>))]
[JsonSerializable(typeof(ApiResult<NotificationDto>))]
[JsonSerializable(typeof(ApiResult<StorageStrategyDto>))]
[JsonSerializable(typeof(ApiResult<TenantFileDto>))]
[JsonSerializable(typeof(ApiResult<FileAccessPolicyDto>))]
[JsonSerializable(typeof(ApiResult<List<PlatformPermissionDto>>))]
[JsonSerializable(typeof(ApiResult<List<TenantGroupDto>>))]
[JsonSerializable(typeof(ApiResult<List<TenantDomainDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<PlatformUserDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<PlatformRoleDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantLifecycleEventDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantTagDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantResourceQuotaDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantFeatureFlagDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantParameterDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<SaasPackageDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<SaasPackageVersionDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<SaasPackageCapabilityDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantSubscriptionDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantTrialDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantSubscriptionChangeDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<BillingInvoiceDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<BillingInvoiceItemDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<PaymentOrderDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<PaymentRefundDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantApiKeyDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantApiUsageStatDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<WebhookEventDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantWebhookDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<WebhookDeliveryLogDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantDailyStatDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<PlatformMonitorMetricDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<OperationLogDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<AuditLogDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<NotificationTemplateDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<NotificationDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<StorageStrategyDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<TenantFileDto>>))]
[JsonSerializable(typeof(ApiResult<PagedResult<FileAccessPolicyDto>>))]
internal partial class TenantPlatformJsonSerializerContext : JsonSerializerContext
{
}
