using System.Linq;
using System.Text;
using YTStdEntity.Generator.Models;

namespace YTStdEntity.Generator.Emitters;

/// <summary>审计查询代码生成器：生成审计查询/历史/比较/主从联合审计查询代码</summary>
internal static class AuditCrudEmitter
{
    /// <summary>生成 {Entity}AuditCRUD.g.cs 内容</summary>
    public static string Emit(EntityModel model)
    {
        var auditTableName = model.TableName + "_audit";

        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using YTStdEntity.Audit;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static partial class {model.ClassName}AuditCRUD");
        sb.AppendLine("    {");

        // AuditTableName const
        sb.AppendLine($"        public const string AuditTableName = \"{auditTableName}\";");
        sb.AppendLine();

        // DiffAuditSnapshots method
        EmitDiffAuditSnapshots(sb, model);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitDiffAuditSnapshots(StringBuilder sb, EntityModel model)
    {
        sb.AppendLine("        /// <summary>Compare two audit snapshots and return field-level differences</summary>");
        sb.AppendLine("        public static List<AuditDiffField> DiffAuditSnapshots(string oldSnapshot, string newSnapshot)");
        sb.AppendLine("        {");
        sb.AppendLine("            var diffs = new List<AuditDiffField>();");
        sb.AppendLine("            using var oldDoc = JsonDocument.Parse(oldSnapshot);");
        sb.AppendLine("            using var newDoc = JsonDocument.Parse(newSnapshot);");
        sb.AppendLine("            var oldRoot = oldDoc.RootElement;");
        sb.AppendLine("            var newRoot = newDoc.RootElement;");
        sb.AppendLine();

        foreach (var col in model.Columns)
        {
            sb.AppendLine($"            {{");
            sb.AppendLine($"                string? oldVal = null;");
            sb.AppendLine($"                string? newVal = null;");
            sb.AppendLine($"                if (oldRoot.TryGetProperty(\"{col.ColumnName}\", out var oldProp) && oldProp.ValueKind != JsonValueKind.Null)");
            sb.AppendLine($"                    oldVal = oldProp.ToString();");
            sb.AppendLine($"                if (newRoot.TryGetProperty(\"{col.ColumnName}\", out var newProp) && newProp.ValueKind != JsonValueKind.Null)");
            sb.AppendLine($"                    newVal = newProp.ToString();");
            sb.AppendLine($"                if (!string.Equals(oldVal, newVal, StringComparison.Ordinal))");
            sb.AppendLine($"                {{");
            sb.AppendLine($"                    diffs.Add(new AuditDiffField");
            sb.AppendLine($"                    {{");
            sb.AppendLine($"                        FieldName = \"{col.ColumnName}\",");
            sb.AppendLine($"                        OldValue = oldVal,");
            sb.AppendLine($"                        NewValue = newVal,");
            sb.AppendLine($"                    }});");
            sb.AppendLine($"                }}");
            sb.AppendLine($"            }}");
        }

        sb.AppendLine("            return diffs;");
        sb.AppendLine("        }");
    }
}
