using System.Collections.Generic;
using System.Linq;
using System.Text;
using YTStdEntity.Generator.Models;

namespace YTStdEntity.Generator.Emitters;

/// <summary>CRUD 代码生成器：生成 Insert/Update/Delete/Get/GetList 代码，调用 DB 方法执行</summary>
internal static class CrudEmitter
{
    /// <summary>生成 {Entity}CRUD.g.cs 内容</summary>
    public static string Emit(EntityModel model)
    {
        var sb = new StringBuilder(8192);
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Npgsql;");
        sb.AppendLine("using NpgsqlTypes;");
        sb.AppendLine("using YTStdAdo;");
        sb.AppendLine("using YTStdEntity;");
        sb.AppendLine("using YTStdLogger.Core;");
        sb.AppendLine("using YTStdSqlBuilder;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>{model.ClassName} CRUD 操作类（编译期生成）</summary>");
        sb.AppendLine($"    public static partial class {model.ClassName}CRUD");
        sb.AppendLine("    {");

        EmitReadEntity(sb, model);
        sb.AppendLine();
        EmitReadEntityPartial(sb, model);
        sb.AppendLine();
        EmitInsertAsync(sb, model);
        sb.AppendLine();
        EmitInsertTxAsync(sb, model);
        sb.AppendLine();
        EmitInsertEntityAsync(sb, model);
        sb.AppendLine();
        EmitInsertEntityTxAsync(sb, model);
        sb.AppendLine();
        EmitUpdateAsync(sb, model);
        sb.AppendLine();
        EmitUpdateTxAsync(sb, model);
        sb.AppendLine();
        EmitUpdateFieldsAsync(sb, model);
        sb.AppendLine();
        EmitUpdateFieldsTxAsync(sb, model);
        sb.AppendLine();
        EmitDeleteAsync(sb, model);
        sb.AppendLine();
        EmitDeleteTxAsync(sb, model);
        sb.AppendLine();
        EmitGetAsync(sb, model);
        sb.AppendLine();
        EmitGetAsyncPartial(sb, model);
        sb.AppendLine();
        EmitIndexMethods(sb, model);
        sb.AppendLine();
        EmitGetListAsync(sb, model);
        sb.AppendLine();
        EmitGetCountAsync(sb, model);
        sb.AppendLine();
        EmitGetPagedListAsync(sb, model);
        sb.AppendLine();
        EmitColumnNameMap(sb, model);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitReadEntity(StringBuilder sb, EntityModel model)
    {
        sb.AppendLine($"        /// <summary>从 NpgsqlDataReader 映射 {model.ClassName} 实体</summary>");
        sb.AppendLine($"        public static {model.ClassName} ReadEntity(NpgsqlDataReader reader)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var entity = new {model.ClassName}();");

        for (int i = 0; i < model.Columns.Count; i++)
        {
            var col = model.Columns[i];
            if (col.IsNullable)
            {
                sb.AppendLine($"            if (!reader.IsDBNull({i}))");
                sb.AppendLine($"                entity.{col.PropertyName} = {GetReaderExpression(col, i)};");
            }
            else
            {
                sb.AppendLine($"            entity.{col.PropertyName} = {GetReaderExpression(col, i)};");
            }
        }

        sb.AppendLine("            return entity;");
        sb.AppendLine("        }");
    }

    private static void EmitInsertAsync(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;
        var tn = model.TableName;
        var pk = model.PrimaryKey;

        // Build column and parameter lists
        var insertCols = model.Columns;
        var colNames = string.Join(",\\n                ", insertCols.Select(c => "\\\"" + c.ColumnName + "\\\""));
        var paramNames = string.Join(",\\n                ", insertCols.Select(c => "@" + c.ColumnName));

        sb.AppendLine($"        /// <summary>插入 {cn}（独立事务）</summary>");
        sb.AppendLine($"        public static async ValueTask<DbInsResult> InsertAsync(");
        sb.AppendLine($"            int tenantId, long userId, {cn} entity)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () => \"[{cn}CRUD.InsertAsync] 进入方法\");");
        sb.AppendLine();

        // Build SQL as multi-line constant
        sb.AppendLine("            const string sql =");
        sb.AppendLine($"                \"INSERT INTO \\\"{tn}\\\" (\" +");
        EmitColumnList(sb, insertCols, "                ");
        sb.AppendLine($"                \") VALUES (\" +");
        EmitParamList(sb, insertCols, "                ");

        if (pk != null)
            sb.AppendLine($"                \") RETURNING \\\"{pk.ColumnName}\\\"\";");
        else
            sb.AppendLine($"                \")\";");

        sb.AppendLine();

        // Build params
        sb.AppendLine($"            var parameters = new PgSqlParam[{insertCols.Count}];");
        for (int i = 0; i < insertCols.Count; i++)
        {
            var col = insertCols[i];
            var valExpr = col.IsNullable
                ? $"(object?)entity.{col.PropertyName} ?? DBNull.Value"
                : $"entity.{col.PropertyName}";
            sb.AppendLine($"            parameters[{i}] = new PgSqlParam(\"@{col.ColumnName}\", {valExpr}, NpgsqlDbType.{col.NpgsqlDbTypeName});");
        }
        sb.AppendLine();

        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var result = await DB.InsertAsync(sql, parameters, tenantId, userId);");
        sb.AppendLine($"                Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.InsertAsync] 完成, Id={{result.Id}}\");");
        sb.AppendLine("                return result;");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine($"                Logger.Error(tenantId, userId, $\"[{cn}CRUD.InsertAsync] 异常: {{ex}}\");");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    private static void EmitInsertTxAsync(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;
        var tn = model.TableName;
        var pk = model.PrimaryKey;
        var insertCols = model.Columns;

        sb.AppendLine($"        /// <summary>插入 {cn}（事务变体，不提交）</summary>");
        sb.AppendLine($"        public static async ValueTask<DbInsResult> InsertTxAsync(");
        sb.AppendLine($"            NpgsqlBatch batch, int tenantId, long userId, {cn} entity)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () => \"[{cn}CRUD.InsertTxAsync] 进入方法\");");
        sb.AppendLine();

        sb.AppendLine("            const string sql =");
        sb.AppendLine($"                \"INSERT INTO \\\"{tn}\\\" (\" +");
        EmitColumnList(sb, insertCols, "                ");
        sb.AppendLine($"                \") VALUES (\" +");
        EmitParamList(sb, insertCols, "                ");

        if (pk != null)
            sb.AppendLine($"                \") RETURNING \\\"{pk.ColumnName}\\\"\";");
        else
            sb.AppendLine($"                \")\";");

        sb.AppendLine();

        sb.AppendLine($"            var parameters = new PgSqlParam[{insertCols.Count}];");
        for (int i = 0; i < insertCols.Count; i++)
        {
            var col = insertCols[i];
            var valExpr = col.IsNullable
                ? $"(object?)entity.{col.PropertyName} ?? DBNull.Value"
                : $"entity.{col.PropertyName}";
            sb.AppendLine($"            parameters[{i}] = new PgSqlParam(\"@{col.ColumnName}\", {valExpr}, NpgsqlDbType.{col.NpgsqlDbTypeName});");
        }
        sb.AppendLine();

        sb.AppendLine("            return await DB.InsertTxAsync(batch, sql, parameters, tenantId, userId);");
        sb.AppendLine("        }");
    }

    private static void EmitInsertEntityAsync(StringBuilder sb, EntityModel model)
    {
        // This is already the entity version - add a params overload if needed
        // The InsertAsync above IS the entity overload. No separate needed.
    }

    private static void EmitInsertEntityTxAsync(StringBuilder sb, EntityModel model)
    {
        // Already entity overload above
    }

    private static void EmitUpdateAsync(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;
        var tn = model.TableName;
        var pk = model.PrimaryKey;
        var pkCol = pk != null ? pk.ColumnName : "id";
        var pkProp = pk != null ? pk.PropertyName : "Id";

        sb.AppendLine($"        /// <summary>更新 {cn}（独立事务，全字段更新）</summary>");
        sb.AppendLine($"        public static async ValueTask<DbUdqResult> UpdateAsync(");
        sb.AppendLine($"            int tenantId, long userId, {cn} entity)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.UpdateAsync] 进入方法, id={{entity.{pkProp}}}\");");
        sb.AppendLine();

        // Build UPDATE SQL
        var updateCols = model.Columns.Where(c => !c.IsPrimaryKey).ToList();

        sb.AppendLine("            const string sql =");
        sb.AppendLine($"                \"UPDATE \\\"{tn}\\\" SET \" +");
        for (int i = 0; i < updateCols.Count; i++)
        {
            var col = updateCols[i];
            var sep = i < updateCols.Count - 1 ? ", " : " ";
            sb.AppendLine($"                \"\\\"{col.ColumnName}\\\" = @{col.ColumnName}{sep}\" +");
        }
        sb.AppendLine($"                \"WHERE \\\"{pkCol}\\\" = @{pkCol}\";");
        sb.AppendLine();

        // Build params: all columns including PK
        var allCols = new List<ColumnModel>(updateCols);
        if (pk != null) allCols.Add(pk);
        sb.AppendLine($"            var parameters = new PgSqlParam[{allCols.Count}];");
        for (int i = 0; i < allCols.Count; i++)
        {
            var col = allCols[i];
            var valExpr = col.IsNullable
                ? $"(object?)entity.{col.PropertyName} ?? DBNull.Value"
                : $"entity.{col.PropertyName}";
            sb.AppendLine($"            parameters[{i}] = new PgSqlParam(\"@{col.ColumnName}\", {valExpr}, NpgsqlDbType.{col.NpgsqlDbTypeName});");
        }
        sb.AppendLine();

        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var result = await DB.UpdateAsync(sql, parameters, tenantId, userId);");
        sb.AppendLine($"                Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.UpdateAsync] 完成, RowsAffected={{result.RowsAffected}}\");");
        sb.AppendLine("                return result;");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine($"                Logger.Error(tenantId, userId, $\"[{cn}CRUD.UpdateAsync] 异常: {{ex}}\");");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    private static void EmitUpdateTxAsync(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;
        var tn = model.TableName;
        var pk = model.PrimaryKey;
        var pkCol = pk != null ? pk.ColumnName : "id";
        var pkProp = pk != null ? pk.PropertyName : "Id";
        var updateCols = model.Columns.Where(c => !c.IsPrimaryKey).ToList();

        sb.AppendLine($"        /// <summary>更新 {cn}（事务变体，不提交）</summary>");
        sb.AppendLine($"        public static ValueTask UpdateTxAsync(");
        sb.AppendLine($"            NpgsqlBatch batch, int tenantId, long userId, {cn} entity)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.UpdateTxAsync] 进入方法, id={{entity.{pkProp}}}\");");
        sb.AppendLine();

        sb.AppendLine("            const string sql =");
        sb.AppendLine($"                \"UPDATE \\\"{tn}\\\" SET \" +");
        for (int i = 0; i < updateCols.Count; i++)
        {
            var col = updateCols[i];
            var sep = i < updateCols.Count - 1 ? ", " : " ";
            sb.AppendLine($"                \"\\\"{col.ColumnName}\\\" = @{col.ColumnName}{sep}\" +");
        }
        sb.AppendLine($"                \"WHERE \\\"{pkCol}\\\" = @{pkCol}\";");
        sb.AppendLine();

        var allCols = new List<ColumnModel>(updateCols);
        if (pk != null) allCols.Add(pk);
        sb.AppendLine($"            var parameters = new PgSqlParam[{allCols.Count}];");
        for (int i = 0; i < allCols.Count; i++)
        {
            var col = allCols[i];
            var valExpr = col.IsNullable
                ? $"(object?)entity.{col.PropertyName} ?? DBNull.Value"
                : $"entity.{col.PropertyName}";
            sb.AppendLine($"            parameters[{i}] = new PgSqlParam(\"@{col.ColumnName}\", {valExpr}, NpgsqlDbType.{col.NpgsqlDbTypeName});");
        }
        sb.AppendLine();

        sb.AppendLine("            return DB.UpdateTxAsync(batch, sql, parameters, tenantId, userId);");
        sb.AppendLine("        }");
    }

    private static void EmitDeleteAsync(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;
        var tn = model.TableName;
        var pk = model.PrimaryKey;
        var pkCol = pk != null ? pk.ColumnName : "id";
        var pkType = pk != null ? EntityGenerator.GetClrTypeForCode(pk) : "long";
        var pkDbType = pk != null ? pk.NpgsqlDbTypeName : "Bigint";

        sb.AppendLine($"        /// <summary>删除 {cn}（独立事务）</summary>");
        sb.AppendLine($"        public static async ValueTask<DbUdqResult> DeleteAsync(");
        sb.AppendLine($"            int tenantId, long userId, {pkType} id)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.DeleteAsync] 进入方法, id={{id}}\");");
        sb.AppendLine();
        sb.AppendLine($"            const string sql = \"DELETE FROM \\\"{tn}\\\" WHERE \\\"{pkCol}\\\" = @{pkCol}\";");
        sb.AppendLine();
        sb.AppendLine($"            var parameters = new PgSqlParam[]");
        sb.AppendLine("            {");
        sb.AppendLine($"                new PgSqlParam(\"@{pkCol}\", id, NpgsqlDbType.{pkDbType})");
        sb.AppendLine("            };");
        sb.AppendLine();
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var result = await DB.DeleteAsync(sql, parameters, tenantId, userId);");
        sb.AppendLine($"                Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.DeleteAsync] 完成, RowsAffected={{result.RowsAffected}}\");");
        sb.AppendLine("                return result;");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine($"                Logger.Error(tenantId, userId, $\"[{cn}CRUD.DeleteAsync] 异常: {{ex}}\");");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    private static void EmitDeleteTxAsync(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;
        var tn = model.TableName;
        var pk = model.PrimaryKey;
        var pkCol = pk != null ? pk.ColumnName : "id";
        var pkType = pk != null ? EntityGenerator.GetClrTypeForCode(pk) : "long";
        var pkDbType = pk != null ? pk.NpgsqlDbTypeName : "Bigint";

        sb.AppendLine($"        /// <summary>删除 {cn}（事务变体，不提交）</summary>");
        sb.AppendLine($"        public static ValueTask DeleteTxAsync(");
        sb.AppendLine($"            NpgsqlBatch batch, int tenantId, long userId, {pkType} id)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.DeleteTxAsync] 进入方法, id={{id}}\");");
        sb.AppendLine();
        sb.AppendLine($"            const string sql = \"DELETE FROM \\\"{tn}\\\" WHERE \\\"{pkCol}\\\" = @{pkCol}\";");
        sb.AppendLine();
        sb.AppendLine($"            var parameters = new PgSqlParam[]");
        sb.AppendLine("            {");
        sb.AppendLine($"                new PgSqlParam(\"@{pkCol}\", id, NpgsqlDbType.{pkDbType})");
        sb.AppendLine("            };");
        sb.AppendLine();
        sb.AppendLine("            return DB.DeleteTxAsync(batch, sql, parameters, tenantId, userId);");
        sb.AppendLine("        }");
    }

    private static void EmitGetAsync(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;
        var tn = model.TableName;
        var pk = model.PrimaryKey;
        var pkCol = pk != null ? pk.ColumnName : "id";
        var pkType = pk != null ? EntityGenerator.GetClrTypeForCode(pk) : "long";
        var pkDbType = pk != null ? pk.NpgsqlDbTypeName : "Bigint";

        sb.AppendLine($"        /// <summary>按主键查询 {cn}，返回单个实体</summary>");
        sb.AppendLine($"        public static async ValueTask<{cn}?> GetAsync(");
        sb.AppendLine($"            int tenantId, long userId, {pkType} id)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.GetAsync] 进入方法, id={{id}}\");");
        sb.AppendLine();

        // Build SELECT SQL
        sb.AppendLine("            const string sql =");
        sb.AppendLine($"                \"SELECT \" +");
        EmitSelectColumnList(sb, model.Columns, "                ");
        sb.AppendLine($"                \"FROM \\\"{tn}\\\" \" +");
        sb.AppendLine($"                \"WHERE \\\"{pkCol}\\\" = @{pkCol}\";");
        sb.AppendLine();

        sb.AppendLine($"            var parameters = new PgSqlParam[]");
        sb.AppendLine("            {");
        sb.AppendLine($"                new PgSqlParam(\"@{pkCol}\", id, NpgsqlDbType.{pkDbType})");
        sb.AppendLine("            };");
        sb.AppendLine();

        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine($"                var (result, data) = await DB.GetListAsync<{cn}>(sql, parameters, ReadEntity, tenantId, userId);");
        sb.AppendLine($"                var entity = (data != null && data.Count > 0) ? data[0] : null;");
        sb.AppendLine($"                Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.GetAsync] 完成, found={{entity != null}}\");");
        sb.AppendLine("                return entity;");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine($"                Logger.Error(tenantId, userId, $\"[{cn}CRUD.GetAsync] 异常: {{ex}}\");");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    private static void EmitGetListAsync(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;
        var tn = model.TableName;

        sb.AppendLine($"        /// <summary>查询 {cn} 列表</summary>");
        sb.AppendLine($"        public static async ValueTask<(DbUdqResult Result, List<{cn}>? Data)> GetListAsync(");
        sb.AppendLine($"            int tenantId, long userId)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () => \"[{cn}CRUD.GetListAsync] 进入方法\");");
        sb.AppendLine();

        sb.AppendLine("            const string sql =");
        sb.AppendLine($"                \"SELECT \" +");
        EmitSelectColumnList(sb, model.Columns, "                ");
        sb.AppendLine($"                \"FROM \\\"{tn}\\\"\";");
        sb.AppendLine();

        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine($"                var (result, data) = await DB.GetListAsync<{cn}>(");
        sb.AppendLine($"                    sql, System.Array.Empty<PgSqlParam>(), ReadEntity, tenantId, userId);");
        sb.AppendLine($"                Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.GetListAsync] 完成, 记录数={{data?.Count ?? 0}}\");");
        sb.AppendLine("                return (result, data);");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine($"                Logger.Error(tenantId, userId, $\"[{cn}CRUD.GetListAsync] 异常: {{ex}}\");");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    // Helper: emit column list for INSERT
    private static void EmitColumnList(StringBuilder sb, List<ColumnModel> cols, string indent)
    {
        for (int i = 0; i < cols.Count; i++)
        {
            var sep = i < cols.Count - 1 ? ", " : "";
            if (i == 0)
                sb.AppendLine($"{indent}\"\\\"" + cols[i].ColumnName + "\\\"" + sep + "\" +");
            else
                sb.AppendLine($"{indent}\"\\\"" + cols[i].ColumnName + "\\\"" + sep + "\" +");
        }
    }

    // Helper: emit parameter list for INSERT VALUES
    private static void EmitParamList(StringBuilder sb, List<ColumnModel> cols, string indent)
    {
        for (int i = 0; i < cols.Count; i++)
        {
            var sep = i < cols.Count - 1 ? ", " : "";
            sb.AppendLine($"{indent}\"@" + cols[i].ColumnName + sep + "\" +");
        }
    }

    // Helper: emit select column list
    private static void EmitSelectColumnList(StringBuilder sb, List<ColumnModel> cols, string indent)
    {
        for (int i = 0; i < cols.Count; i++)
        {
            var sep = i < cols.Count - 1 ? ", " : " ";
            sb.AppendLine($"{indent}\"\\\"" + cols[i].ColumnName + "\\\"" + sep + "\" +");
        }
    }

    private static string GetReaderExpression(ColumnModel col, int ordinal)
    {
        if (EntityGenerator.NeedsGenericReader(col))
        {
            return "reader.GetFieldValue<" + EntityGenerator.GetClrTypeForCode(col) + ">(" + ordinal + ")";
        }
        return $"reader.{EntityGenerator.GetReaderMethod(col)}({ordinal})";
    }

    private static void EmitReadEntityPartial(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;
        sb.AppendLine($"        /// <summary>从 NpgsqlDataReader 按列名映射 {cn} 实体（部分字段）</summary>");
        sb.AppendLine($"        public static {cn} ReadEntityPartial(NpgsqlDataReader reader)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var entity = new {cn}();");
        sb.AppendLine("            for (int i = 0; i < reader.FieldCount; i++)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (reader.IsDBNull(i)) continue;");
        sb.AppendLine("                var colName = reader.GetName(i);");
        sb.AppendLine("                switch (colName)");
        sb.AppendLine("                {");

        for (int i = 0; i < model.Columns.Count; i++)
        {
            var col = model.Columns[i];
            sb.AppendLine($"                    case \"{col.ColumnName}\":");
            sb.AppendLine($"                        entity.{col.PropertyName} = {GetPartialReaderExpression(col)};");
            sb.AppendLine("                        break;");
        }

        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            return entity;");
        sb.AppendLine("        }");
    }

    private static string GetPartialReaderExpression(ColumnModel col)
    {
        if (EntityGenerator.NeedsGenericReader(col))
        {
            return "reader.GetFieldValue<" + EntityGenerator.GetClrTypeForCode(col) + ">(i)";
        }
        return $"reader.{EntityGenerator.GetReaderMethod(col)}(i)";
    }

    private static void EmitUpdateFieldsAsync(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;
        var tn = model.TableName;
        var pk = model.PrimaryKey;
        var pkCol = pk != null ? pk.ColumnName : "id";
        var pkType = pk != null ? EntityGenerator.GetClrTypeForCode(pk) : "long";
        var pkDbType = pk != null ? pk.NpgsqlDbTypeName : "Bigint";

        // Scattered parameter fields: exclude PK and tenant_id
        var scatteredCols = model.Columns.Where(c => !c.IsPrimaryKey && !c.IsTenantField).ToList();

        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// 按字段更新 {cn}（打散参数版，独立事务）。");
        sb.AppendLine($"        /// 参数使用 DbNullable&lt;T&gt;? 包装：null 表示不更新，DbNullable.NullValue 表示设置为 NULL。");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        public static async ValueTask<DbUdqResult> UpdateFieldsAsync(");
        sb.Append($"            int tenantId, long userId, {pkType} id");

        foreach (var col in scatteredCols)
        {
            var clrType = EntityGenerator.GetClrTypeForCode(col);
            sb.AppendLine(",");
            sb.Append($"            DbNullable<{clrType}>? {ToCamelCase(col.PropertyName)} = null");
        }
        sb.AppendLine(")");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.UpdateFieldsAsync] 进入方法, id={{id}}\");");
        sb.AppendLine();

        // Dynamic SQL building
        sb.AppendLine("            var setClauses = new System.Collections.Generic.List<string>();");
        sb.AppendLine("            var paramList = new System.Collections.Generic.List<PgSqlParam>();");
        sb.AppendLine();

        foreach (var col in scatteredCols)
        {
            var camel = ToCamelCase(col.PropertyName);
            sb.AppendLine($"            if ({camel}.HasValue && {camel}.Value.IsSet)");
            sb.AppendLine("            {");
            sb.AppendLine($"                setClauses.Add(\"\\\"{col.ColumnName}\\\" = @{col.ColumnName}\");");
            sb.AppendLine($"                paramList.Add(new PgSqlParam(\"@{col.ColumnName}\", (object?){camel}.Value.Value ?? DBNull.Value, NpgsqlDbType.{col.NpgsqlDbTypeName}));");
            sb.AppendLine("            }");
            sb.AppendLine();
        }

        sb.AppendLine("            if (setClauses.Count == 0)");
        sb.AppendLine("            {");
        sb.AppendLine($"                Logger.Debug(tenantId, userId, () => \"[{cn}CRUD.UpdateFieldsAsync] 无字段需要更新\");");
        sb.AppendLine("                return new DbUdqResult { Success = true, RowsAffected = 0 };");
        sb.AppendLine("            }");
        sb.AppendLine();

        sb.AppendLine($"            paramList.Add(new PgSqlParam(\"@{pkCol}\", id, NpgsqlDbType.{pkDbType}));");
        sb.AppendLine();
        sb.AppendLine($"            var sql = \"UPDATE \\\"{tn}\\\" SET \" +");
        sb.AppendLine("                string.Join(\", \", setClauses) +");
        sb.AppendLine($"                \" WHERE \\\"{pkCol}\\\" = @{pkCol}\";");
        sb.AppendLine();

        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var result = await DB.UpdateAsync(sql, paramList.ToArray(), tenantId, userId);");
        sb.AppendLine($"                Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.UpdateFieldsAsync] 完成, RowsAffected={{result.RowsAffected}}\");");
        sb.AppendLine("                return result;");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine($"                Logger.Error(tenantId, userId, $\"[{cn}CRUD.UpdateFieldsAsync] 异常: {{ex}}\");");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    private static void EmitUpdateFieldsTxAsync(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;
        var tn = model.TableName;
        var pk = model.PrimaryKey;
        var pkCol = pk != null ? pk.ColumnName : "id";
        var pkType = pk != null ? EntityGenerator.GetClrTypeForCode(pk) : "long";
        var pkDbType = pk != null ? pk.NpgsqlDbTypeName : "Bigint";

        var scatteredCols = model.Columns.Where(c => !c.IsPrimaryKey && !c.IsTenantField).ToList();

        sb.AppendLine($"        /// <summary>按字段更新 {cn}（打散参数版，事务变体）</summary>");
        sb.AppendLine($"        public static ValueTask UpdateFieldsTxAsync(");
        sb.Append($"            NpgsqlBatch batch, int tenantId, long userId, {pkType} id");

        foreach (var col in scatteredCols)
        {
            var clrType = EntityGenerator.GetClrTypeForCode(col);
            sb.AppendLine(",");
            sb.Append($"            DbNullable<{clrType}>? {ToCamelCase(col.PropertyName)} = null");
        }
        sb.AppendLine(")");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.UpdateFieldsTxAsync] 进入方法, id={{id}}\");");
        sb.AppendLine();

        sb.AppendLine("            var setClauses = new System.Collections.Generic.List<string>();");
        sb.AppendLine("            var paramList = new System.Collections.Generic.List<PgSqlParam>();");
        sb.AppendLine();

        foreach (var col in scatteredCols)
        {
            var camel = ToCamelCase(col.PropertyName);
            sb.AppendLine($"            if ({camel}.HasValue && {camel}.Value.IsSet)");
            sb.AppendLine("            {");
            sb.AppendLine($"                setClauses.Add(\"\\\"{col.ColumnName}\\\" = @{col.ColumnName}\");");
            sb.AppendLine($"                paramList.Add(new PgSqlParam(\"@{col.ColumnName}\", (object?){camel}.Value.Value ?? DBNull.Value, NpgsqlDbType.{col.NpgsqlDbTypeName}));");
            sb.AppendLine("            }");
            sb.AppendLine();
        }

        sb.AppendLine("            if (setClauses.Count == 0)");
        sb.AppendLine("            {");
        sb.AppendLine($"                Logger.Debug(tenantId, userId, () => \"[{cn}CRUD.UpdateFieldsTxAsync] 无字段需要更新\");");
        sb.AppendLine("                return ValueTask.CompletedTask;");
        sb.AppendLine("            }");
        sb.AppendLine();

        sb.AppendLine($"            paramList.Add(new PgSqlParam(\"@{pkCol}\", id, NpgsqlDbType.{pkDbType}));");
        sb.AppendLine();
        sb.AppendLine($"            var sql = \"UPDATE \\\"{tn}\\\" SET \" +");
        sb.AppendLine("                string.Join(\", \", setClauses) +");
        sb.AppendLine($"                \" WHERE \\\"{pkCol}\\\" = @{pkCol}\";");
        sb.AppendLine();

        sb.AppendLine("            return DB.UpdateTxAsync(batch, sql, paramList.ToArray(), tenantId, userId);");
        sb.AppendLine("        }");
    }

    private static void EmitGetAsyncPartial(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;
        var tn = model.TableName;
        var pk = model.PrimaryKey;
        var pkCol = pk != null ? pk.ColumnName : "id";
        var pkType = pk != null ? EntityGenerator.GetClrTypeForCode(pk) : "long";
        var pkDbType = pk != null ? pk.NpgsqlDbTypeName : "Bigint";

        sb.AppendLine($"        /// <summary>按主键查询 {cn}，仅返回指定字段</summary>");
        sb.AppendLine($"        public static async ValueTask<{cn}?> GetAsync(");
        sb.AppendLine($"            int tenantId, long userId, {pkType} id, params string[] columns)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.GetAsync(partial)] 进入方法, id={{id}}, columns={{string.Join(\",\", columns)}}\");");
        sb.AppendLine();

        sb.AppendLine("            if (columns == null || columns.Length == 0)");
        sb.AppendLine("            {");
        sb.AppendLine("                return await GetAsync(tenantId, userId, id);");
        sb.AppendLine("            }");
        sb.AppendLine();

        // Build dynamic SQL with only specified columns
        sb.AppendLine("            var quotedCols = new string[columns.Length];");
        sb.AppendLine("            for (int i = 0; i < columns.Length; i++)");
        sb.AppendLine("            {");
        sb.AppendLine("                quotedCols[i] = \"\\\"\" + columns[i] + \"\\\"\";");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine($"            var sql = \"SELECT \" + string.Join(\", \", quotedCols) +");
        sb.AppendLine($"                \" FROM \\\"{tn}\\\" WHERE \\\"{pkCol}\\\" = @{pkCol}\";");
        sb.AppendLine();

        sb.AppendLine($"            var parameters = new PgSqlParam[]");
        sb.AppendLine("            {");
        sb.AppendLine($"                new PgSqlParam(\"@{pkCol}\", id, NpgsqlDbType.{pkDbType})");
        sb.AppendLine("            };");
        sb.AppendLine();

        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine($"                var (result, data) = await DB.GetListAsync<{cn}>(sql, parameters, ReadEntityPartial, tenantId, userId);");
        sb.AppendLine($"                var entity = (data != null && data.Count > 0) ? data[0] : null;");
        sb.AppendLine($"                Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.GetAsync(partial)] 完成, found={{entity != null}}\");");
        sb.AppendLine("                return entity;");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine($"                Logger.Error(tenantId, userId, $\"[{cn}CRUD.GetAsync(partial)] 异常: {{ex}}\");");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    private static void EmitIndexMethods(StringBuilder sb, EntityModel model)
    {
        if (model.Indexes.Count == 0)
        {
            return;
        }

        var emitted = false;
        for (int i = 0; i < model.Indexes.Count; i++)
        {
            var index = model.Indexes[i];
            var indexColumns = ResolveIndexColumns(model, index);
            if (indexColumns.Count == 0)
            {
                continue;
            }

            if (emitted)
            {
                sb.AppendLine();
            }

            if (index.IsUnique)
            {
                EmitUniqueIndexMethod(sb, model, index, indexColumns);
            }
            else
            {
                EmitNormalIndexMethod(sb, model, index, indexColumns);
                sb.AppendLine();
                EmitIndexPagedMethod(sb, model, index, indexColumns);
            }

            emitted = true;
        }

        // Emit prefix-based ordered index methods for composite indexes
        for (int i = 0; i < model.Indexes.Count; i++)
        {
            var index = model.Indexes[i];
            if (index.Columns.Length < 2)
                continue;
            var indexColumns = ResolveIndexColumns(model, index);
            if (indexColumns.Count < 2)
                continue;

            // Generate method for querying by first column of composite index
            sb.AppendLine();
            EmitIndexPrefixMethod(sb, model, index, indexColumns);
        }
    }

    private static void EmitUniqueIndexMethod(StringBuilder sb, EntityModel model, IndexModel index, List<ColumnModel> indexColumns)
    {
        var cn = model.ClassName;
        var methodName = GetIndexMethodName(index.IndexName);

        sb.AppendLine($"        /// <summary>按唯一索引 {index.IndexName} 查询 {cn}，返回单个实体</summary>");
        sb.AppendLine($"        public static async ValueTask<{cn}?> {methodName}(");
        EmitIndexMethodParameters(sb, indexColumns);
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.{methodName}] 进入方法, columns={{string.Join(\",\", columns)}}\");");
        sb.AppendLine();
        EmitIndexMethodBody(sb, model, indexColumns, methodName, true);
        sb.AppendLine("        }");
    }

    private static void EmitNormalIndexMethod(StringBuilder sb, EntityModel model, IndexModel index, List<ColumnModel> indexColumns)
    {
        var cn = model.ClassName;
        var methodName = GetIndexMethodName(index.IndexName);

        sb.AppendLine($"        /// <summary>按索引 {index.IndexName} 查询 {cn} 列表</summary>");
        sb.AppendLine($"        public static async ValueTask<List<{cn}>?> {methodName}(");
        EmitIndexMethodParameters(sb, indexColumns);
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.{methodName}] 进入方法, columns={{string.Join(\",\", columns)}}\");");
        sb.AppendLine();
        EmitIndexMethodBody(sb, model, indexColumns, methodName, false);
        sb.AppendLine("        }");
    }

    private static void EmitIndexMethodParameters(StringBuilder sb, List<ColumnModel> indexColumns)
    {
        sb.AppendLine("            int tenantId, long userId,");
        for (int i = 0; i < indexColumns.Count; i++)
        {
            var col = indexColumns[i];
            sb.AppendLine($"            {GetMethodParameterType(col)} {ToCamelCase(col.PropertyName)},");
        }
        sb.AppendLine("            params string[] columns)");
    }

    private static void EmitIndexMethodBody(StringBuilder sb, EntityModel model, List<ColumnModel> indexColumns, string methodName, bool single)
    {
        var cn = model.ClassName;
        var tn = model.TableName;
        var whereClause = BuildIndexWhereClause(indexColumns);

        sb.AppendLine("            if (columns == null || columns.Length == 0)");
        sb.AppendLine("            {");
        sb.AppendLine("                const string sql =");
        sb.AppendLine("                    \"SELECT \" +");
        EmitSelectColumnList(sb, model.Columns, "                    ");
        sb.AppendLine($"                    \"FROM \\\"{tn}\\\" WHERE {whereClause}\";");
        sb.AppendLine();
        EmitIndexParameters(sb, indexColumns, "                ", "parameters");
        sb.AppendLine();
        sb.AppendLine("                try");
        sb.AppendLine("                {");
        sb.AppendLine($"                    var (result, data) = await DB.GetListAsync<{cn}>(sql, parameters, ReadEntity, tenantId, userId);");
        if (single)
        {
            sb.AppendLine("                    var entity = (data != null && data.Count > 0) ? data[0] : null;");
            sb.AppendLine($"                    Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.{methodName}] 完成, found={{entity != null}}\");");
            sb.AppendLine("                    return entity;");
        }
        else
        {
            sb.AppendLine($"                    Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.{methodName}] 完成, 记录数={{data?.Count ?? 0}}\");");
            sb.AppendLine("                    return data;");
        }
        sb.AppendLine("                }");
        sb.AppendLine("                catch (Exception ex)");
        sb.AppendLine("                {");
        sb.AppendLine($"                    Logger.Error(tenantId, userId, $\"[{cn}CRUD.{methodName}] 异常: {{ex}}\");");
        sb.AppendLine("                    throw;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            var quotedCols = new string[columns.Length];");
        sb.AppendLine("            for (int i = 0; i < columns.Length; i++)");
        sb.AppendLine("            {");
        sb.AppendLine("                quotedCols[i] = \"\\\"\" + columns[i] + \"\\\"\";");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine($"            var partialSql = \"SELECT \" + string.Join(\", \", quotedCols) + \" FROM \\\"{tn}\\\" WHERE {whereClause}\";");
        sb.AppendLine();
        EmitIndexParameters(sb, indexColumns, "            ", "partialParameters");
        sb.AppendLine();
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine($"                var (result, data) = await DB.GetListAsync<{cn}>(partialSql, partialParameters, ReadEntityPartial, tenantId, userId);");
        if (single)
        {
            sb.AppendLine("                var entity = (data != null && data.Count > 0) ? data[0] : null;");
            sb.AppendLine($"                Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.{methodName}] 完成, found={{entity != null}}\");");
            sb.AppendLine("                return entity;");
        }
        else
        {
            sb.AppendLine($"                Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.{methodName}] 完成, 记录数={{data?.Count ?? 0}}\");");
            sb.AppendLine("                return data;");
        }
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine($"                Logger.Error(tenantId, userId, $\"[{cn}CRUD.{methodName}] 异常: {{ex}}\");");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
    }

    private static void EmitIndexParameters(StringBuilder sb, List<ColumnModel> indexColumns, string indent, string variableName)
    {
        sb.AppendLine($"{indent}var {variableName} = new PgSqlParam[]");
        sb.AppendLine($"{indent}{{");
        for (int i = 0; i < indexColumns.Count; i++)
        {
            var col = indexColumns[i];
            var valueExpr = col.IsNullable
                ? $"(object?){ToCamelCase(col.PropertyName)} ?? DBNull.Value"
                : ToCamelCase(col.PropertyName);
            var suffix = i < indexColumns.Count - 1 ? "," : string.Empty;
            sb.AppendLine($"{indent}    new PgSqlParam(\"@{col.ColumnName}\", {valueExpr}, NpgsqlDbType.{col.NpgsqlDbTypeName}){suffix}");
        }
        sb.AppendLine($"{indent}}};");
    }

    private static List<ColumnModel> ResolveIndexColumns(EntityModel model, IndexModel index)
    {
        var result = new List<ColumnModel>(index.Columns.Length);
        for (int i = 0; i < index.Columns.Length; i++)
        {
            var indexColumnName = index.Columns[i];
            ColumnModel? matched = null;
            for (int j = 0; j < model.Columns.Count; j++)
            {
                var col = model.Columns[j];
                if (col.ColumnName == indexColumnName)
                {
                    matched = col;
                    break;
                }
            }

            if (matched == null)
            {
                return new List<ColumnModel>();
            }

            result.Add(matched);
        }

        return result;
    }

    private static string BuildIndexWhereClause(List<ColumnModel> indexColumns)
    {
        var sb = new StringBuilder();
        for (int i = 0; i < indexColumns.Count; i++)
        {
            if (i > 0)
            {
                sb.Append(" AND ");
            }

            sb.Append("\\\"");
            sb.Append(indexColumns[i].ColumnName);
            sb.Append("\\\" = @");
            sb.Append(indexColumns[i].ColumnName);
        }

        return sb.ToString();
    }

    private static string GetMethodParameterType(ColumnModel col)
    {
        var clrType = EntityGenerator.GetClrTypeForCode(col);
        if (!col.IsNullable)
        {
            return clrType;
        }

        if (clrType.EndsWith("?"))
        {
            return clrType;
        }

        return clrType + "?";
    }

    private static string GetIndexMethodName(string indexName)
    {
        if (string.IsNullOrWhiteSpace(indexName))
        {
            return "Index";
        }

        var result = new StringBuilder(indexName.Length + 1);
        var first = indexName[0];
        if (char.IsLetter(first) || first == '_')
        {
            result.Append(first);
        }
        else
        {
            result.Append('_');
            if (char.IsLetterOrDigit(first))
            {
                result.Append(first);
            }
        }

        for (int i = 1; i < indexName.Length; i++)
        {
            var ch = indexName[i];
            result.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
        }

        return result.ToString();
    }

    private static string ToCamelCase(string propertyName)
    {
        if (string.IsNullOrEmpty(propertyName)) return propertyName;
        var camel = char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1);
        // Avoid conflict with method parameters tenantId, userId, id, batch, columns
        if (camel == "tenantId" || camel == "userId" || camel == "id" || camel == "batch" || camel == "columns")
            return "field_" + camel;
        return camel;
    }

    /// <summary>为非唯一索引生成分页查询方法</summary>
    private static void EmitIndexPagedMethod(StringBuilder sb, EntityModel model, IndexModel index, List<ColumnModel> indexColumns)
    {
        var cn = model.ClassName;
        var tn = model.TableName;
        var methodName = GetIndexMethodName(index.IndexName) + "_Paged";
        var whereClause = BuildIndexWhereClause(indexColumns);

        sb.AppendLine($"        /// <summary>按索引 {index.IndexName} 分页查询 {cn} 列表，支持多字段排序</summary>");
        sb.AppendLine($"        public static async ValueTask<(DbUdqResult Result, List<{cn}>? Data, long Total)> {methodName}(");
        sb.AppendLine("            int tenantId, long userId,");
        for (int i = 0; i < indexColumns.Count; i++)
        {
            var col = indexColumns[i];
            sb.AppendLine($"            {GetMethodParameterType(col)} {ToCamelCase(col.PropertyName)},");
        }
        sb.AppendLine("            int offset, int limit,");
        sb.AppendLine("            (string Column, bool Descending)[]? sortFields = null)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.{methodName}] 进入方法, offset={{offset}}, limit={{limit}}\");");
        sb.AppendLine();

        // Count
        sb.AppendLine($"            var countSql = \"SELECT COUNT(*) FROM \\\"{tn}\\\" WHERE {whereClause}\";");
        sb.AppendLine();
        EmitIndexParameters(sb, indexColumns, "            ", "parameters");
        sb.AppendLine();

        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var countResult = await DB.GetScalarAsync<long>(countSql, parameters, tenantId, userId);");
        sb.AppendLine("                long total = countResult.Success ? countResult.Value : 0L;");
        sb.AppendLine("                if (total == 0)");
        sb.AppendLine("                {");
        sb.AppendLine($"                    return (new DbUdqResult {{ Success = true }}, new List<{cn}>(), 0);");
        sb.AppendLine("                }");
        sb.AppendLine();

        sb.AppendLine("                var orderClause = BuildOrderByClause(sortFields);");
        sb.AppendLine($"                var sql = \"SELECT \" +");
        EmitSelectColumnList(sb, model.Columns, "                    ");
        sb.AppendLine($"                    \"FROM \\\"{tn}\\\" WHERE {whereClause} \" +");
        sb.AppendLine("                    orderClause +");
        sb.AppendLine($"                    \" LIMIT \" + limit + \" OFFSET \" + offset;");
        sb.AppendLine();

        sb.AppendLine($"                var (result, data) = await DB.GetListAsync<{cn}>(");
        sb.AppendLine($"                    sql, parameters, ReadEntity, tenantId, userId);");
        sb.AppendLine($"                Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.{methodName}] 完成, total={{total}}, 记录数={{data?.Count ?? 0}}\");");
        sb.AppendLine("                return (result, data, total);");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine($"                Logger.Error(tenantId, userId, $\"[{cn}CRUD.{methodName}] 异常: {{ex}}\");");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    /// <summary>为复合索引生成按第一列查询的方法（前缀索引查询）</summary>
    private static void EmitIndexPrefixMethod(StringBuilder sb, EntityModel model, IndexModel index, List<ColumnModel> indexColumns)
    {
        var cn = model.ClassName;
        var tn = model.TableName;
        var firstCol = indexColumns[0];
        var methodName = GetIndexMethodName(index.IndexName) + "_ByFirst";

        sb.AppendLine($"        /// <summary>按索引 {index.IndexName} 的首列 {firstCol.PropertyName} 查询 {cn} 列表（利用复合索引前缀）</summary>");
        sb.AppendLine($"        public static async ValueTask<List<{cn}>?> {methodName}(");
        sb.AppendLine($"            int tenantId, long userId,");
        sb.AppendLine($"            {GetMethodParameterType(firstCol)} {ToCamelCase(firstCol.PropertyName)},");
        sb.AppendLine("            params string[] columns)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.{methodName}] 进入方法\");");
        sb.AppendLine();

        var firstColWhere = "\\\"" + firstCol.ColumnName + "\\\" = @" + firstCol.ColumnName;

        sb.AppendLine("            if (columns == null || columns.Length == 0)");
        sb.AppendLine("            {");
        sb.AppendLine("                const string sql =");
        sb.AppendLine("                    \"SELECT \" +");
        EmitSelectColumnList(sb, model.Columns, "                    ");
        sb.AppendLine($"                    \"FROM \\\"{tn}\\\" WHERE {firstColWhere}\";");
        sb.AppendLine();
        EmitIndexParameters(sb, new List<ColumnModel> { firstCol }, "                ", "parameters");
        sb.AppendLine();
        sb.AppendLine("                try");
        sb.AppendLine("                {");
        sb.AppendLine($"                    var (result, data) = await DB.GetListAsync<{cn}>(sql, parameters, ReadEntity, tenantId, userId);");
        sb.AppendLine($"                    Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.{methodName}] 完成, 记录数={{data?.Count ?? 0}}\");");
        sb.AppendLine("                    return data;");
        sb.AppendLine("                }");
        sb.AppendLine("                catch (Exception ex)");
        sb.AppendLine("                {");
        sb.AppendLine($"                    Logger.Error(tenantId, userId, $\"[{cn}CRUD.{methodName}] 异常: {{ex}}\");");
        sb.AppendLine("                    throw;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            var quotedCols = new string[columns.Length];");
        sb.AppendLine("            for (int i = 0; i < columns.Length; i++)");
        sb.AppendLine("            {");
        sb.AppendLine("                quotedCols[i] = \"\\\"\" + columns[i] + \"\\\"\";");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine($"            var partialSql = \"SELECT \" + string.Join(\", \", quotedCols) + \" FROM \\\"{tn}\\\" WHERE {firstColWhere}\";");
        sb.AppendLine();
        EmitIndexParameters(sb, new List<ColumnModel> { firstCol }, "            ", "partialParameters");
        sb.AppendLine();
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine($"                var (result, data) = await DB.GetListAsync<{cn}>(partialSql, partialParameters, ReadEntityPartial, tenantId, userId);");
        sb.AppendLine($"                Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.{methodName}] 完成, 记录数={{data?.Count ?? 0}}\");");
        sb.AppendLine("                return data;");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine($"                Logger.Error(tenantId, userId, $\"[{cn}CRUD.{methodName}] 异常: {{ex}}\");");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    private static void EmitGetCountAsync(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;
        var tn = model.TableName;

        sb.AppendLine($"        /// <summary>查询 {cn} 总记录数</summary>");
        sb.AppendLine($"        public static async ValueTask<long> GetCountAsync(");
        sb.AppendLine($"            int tenantId, long userId)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () => \"[{cn}CRUD.GetCountAsync] 进入方法\");");
        sb.AppendLine();
        sb.AppendLine($"            const string sql = \"SELECT COUNT(*) FROM \\\"{tn}\\\"\";");
        sb.AppendLine();
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var result = await DB.GetScalarAsync<long>(sql, System.Array.Empty<PgSqlParam>(), tenantId, userId);");
        sb.AppendLine($"                Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.GetCountAsync] 完成, count={{result.Value}}\");");
        sb.AppendLine("                return result.Success ? result.Value : 0L;");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine($"                Logger.Error(tenantId, userId, $\"[{cn}CRUD.GetCountAsync] 异常: {{ex}}\");");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    private static void EmitGetPagedListAsync(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;
        var tn = model.TableName;
        var pk = model.PrimaryKey;
        var pkCol = pk != null ? pk.ColumnName : "id";

        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// 分页查询 {cn} 列表，支持多字段排序。");
        sb.AppendLine($"        /// sortFields 格式：(columnName, descending) 元组数组，按索引顺序排列。");
        sb.AppendLine($"        /// 传入 null 或空数组时默认按主键升序。");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        public static async ValueTask<(DbUdqResult Result, List<{cn}>? Data, long Total)> GetPagedListAsync(");
        sb.AppendLine($"            int tenantId, long userId,");
        sb.AppendLine($"            int offset, int limit,");
        sb.AppendLine($"            (string Column, bool Descending)[]? sortFields = null)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.GetPagedListAsync] 进入方法, offset={{offset}}, limit={{limit}}\");");
        sb.AppendLine();

        // Count query
        sb.AppendLine($"            const string countSql = \"SELECT COUNT(*) FROM \\\"{tn}\\\"\";");
        sb.AppendLine();
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                // 1. 查询总数");
        sb.AppendLine("                var countResult = await DB.GetScalarAsync<long>(countSql, System.Array.Empty<PgSqlParam>(), tenantId, userId);");
        sb.AppendLine("                long total = countResult.Success ? countResult.Value : 0L;");
        sb.AppendLine("                if (total == 0)");
        sb.AppendLine("                {");
        sb.AppendLine($"                    Logger.Debug(tenantId, userId, () => \"[{cn}CRUD.GetPagedListAsync] 总数为0，跳过数据查询\");");
        sb.AppendLine($"                    return (new DbUdqResult {{ Success = true }}, new List<{cn}>(), 0);");
        sb.AppendLine("                }");
        sb.AppendLine();

        // Build ORDER BY
        sb.AppendLine("                // 2. 构建排序和分页 SQL");
        sb.AppendLine("                var orderClause = BuildOrderByClause(sortFields);");
        sb.AppendLine($"                var sql = \"SELECT \" +");
        EmitSelectColumnList(sb, model.Columns, "                    ");
        sb.AppendLine($"                    \"FROM \\\"{tn}\\\" \" +");
        sb.AppendLine("                    orderClause +");
        sb.AppendLine($"                    \" LIMIT \" + limit + \" OFFSET \" + offset;");
        sb.AppendLine();

        // Execute query
        sb.AppendLine("                // 3. 查询分页数据");
        sb.AppendLine($"                var (result, data) = await DB.GetListAsync<{cn}>(");
        sb.AppendLine($"                    sql, System.Array.Empty<PgSqlParam>(), ReadEntity, tenantId, userId);");
        sb.AppendLine($"                Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.GetPagedListAsync] 完成, total={{total}}, 记录数={{data?.Count ?? 0}}\");");
        sb.AppendLine("                return (result, data, total);");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine($"                Logger.Error(tenantId, userId, $\"[{cn}CRUD.GetPagedListAsync] 异常: {{ex}}\");");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Emit overload with SQL WHERE condition
        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// 分页查询 {cn} 列表（带 WHERE 条件），支持多字段排序。");
        sb.AppendLine($"        /// whereClause 不含 WHERE 关键字（例如 \"\\\"status\\\" = @status\"）。");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        public static async ValueTask<(DbUdqResult Result, List<{cn}>? Data, long Total)> GetPagedListAsync(");
        sb.AppendLine($"            int tenantId, long userId,");
        sb.AppendLine($"            int offset, int limit,");
        sb.AppendLine($"            string whereClause, PgSqlParam[] parameters,");
        sb.AppendLine($"            (string Column, bool Descending)[]? sortFields = null)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.GetPagedListAsync(where)] 进入方法, offset={{offset}}, limit={{limit}}\");");
        sb.AppendLine();

        sb.AppendLine($"            var countSql = \"SELECT COUNT(*) FROM \\\"{tn}\\\" WHERE \" + whereClause;");
        sb.AppendLine();
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                // 1. 查询满足条件的总数");
        sb.AppendLine("                var countResult = await DB.GetScalarAsync<long>(countSql, parameters, tenantId, userId);");
        sb.AppendLine("                long total = countResult.Success ? countResult.Value : 0L;");
        sb.AppendLine("                if (total == 0)");
        sb.AppendLine("                {");
        sb.AppendLine($"                    Logger.Debug(tenantId, userId, () => \"[{cn}CRUD.GetPagedListAsync(where)] 总数为0，跳过数据查询\");");
        sb.AppendLine($"                    return (new DbUdqResult {{ Success = true }}, new List<{cn}>(), 0);");
        sb.AppendLine("                }");
        sb.AppendLine();

        sb.AppendLine("                // 2. 构建排序和分页 SQL");
        sb.AppendLine("                var orderClause = BuildOrderByClause(sortFields);");
        sb.AppendLine($"                var sql = \"SELECT \" +");
        EmitSelectColumnList(sb, model.Columns, "                    ");
        sb.AppendLine($"                    \"FROM \\\"{tn}\\\" WHERE \" + whereClause + \" \" +");
        sb.AppendLine("                    orderClause +");
        sb.AppendLine($"                    \" LIMIT \" + limit + \" OFFSET \" + offset;");
        sb.AppendLine();

        sb.AppendLine("                // 3. 查询分页数据");
        sb.AppendLine($"                var (result, data) = await DB.GetListAsync<{cn}>(");
        sb.AppendLine($"                    sql, parameters, ReadEntity, tenantId, userId);");
        sb.AppendLine($"                Logger.Debug(tenantId, userId, () => $\"[{cn}CRUD.GetPagedListAsync(where)] 完成, total={{total}}, 记录数={{data?.Count ?? 0}}\");");
        sb.AppendLine("                return (result, data, total);");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine($"                Logger.Error(tenantId, userId, $\"[{cn}CRUD.GetPagedListAsync(where)] 异常: {{ex}}\");");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    private static void EmitColumnNameMap(StringBuilder sb, EntityModel model)
    {
        var cn = model.ClassName;

        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// {cn} 属性名到数据库列名的映射字典。");
        sb.AppendLine($"        /// 用于排序时将前端传入的属性名转换为安全的数据库列名，防止 SQL 注入。");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        public static readonly System.Collections.Generic.Dictionary<string, string> ColumnNameMap = new(System.StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("        {");
        for (int i = 0; i < model.Columns.Count; i++)
        {
            var col = model.Columns[i];
            var sep = i < model.Columns.Count - 1 ? "," : "";
            sb.AppendLine($"            {{ \"{col.PropertyName}\", \"{col.ColumnName}\" }}{sep}");
        }
        sb.AppendLine("        };");
        sb.AppendLine();

        // Static helper: build ORDER BY clause from sort fields with validation
        sb.AppendLine($"        /// <summary>根据排序字段数组构建 ORDER BY 子句（含 SQL 注入防护）</summary>");
        sb.AppendLine($"        private static string BuildOrderByClause((string Column, bool Descending)[]? sortFields)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (sortFields == null || sortFields.Length == 0)");
        sb.AppendLine("            {");
        // Default sort: by PK ASC
        sb.AppendLine($"                return \"ORDER BY \\\"{model.Columns[0].ColumnName}\\\" ASC\";");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            var parts = new System.Collections.Generic.List<string>(sortFields.Length);");
        sb.AppendLine("            for (int i = 0; i < sortFields.Length; i++)");
        sb.AppendLine("            {");
        sb.AppendLine("                var field = sortFields[i];");
        sb.AppendLine("                if (ColumnNameMap.TryGetValue(field.Column, out var dbCol))");
        sb.AppendLine("                {");
        sb.AppendLine("                    parts.Add(\"\\\"\" + dbCol + \"\\\" \" + (field.Descending ? \"DESC\" : \"ASC\"));");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            if (parts.Count == 0)");
        sb.AppendLine("            {");
        sb.AppendLine($"                return \"ORDER BY \\\"{model.Columns[0].ColumnName}\\\" ASC\";");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return \"ORDER BY \" + string.Join(\", \", parts);");
        sb.AppendLine("        }");
    }
}
