using System.Collections.Generic;
using System.Linq;
using System.Text;
using YTStdEntity.Generator.Models;

namespace YTStdEntity.Generator.Emitters;

/// <summary>CRUD 代码生成器：生成 Insert/Update/Delete/Get/GetList 代码</summary>
internal static class CrudEmitter
{
    /// <summary>生成 {Entity}CRUD.g.cs 内容</summary>
    public static string Emit(EntityModel model)
    {
        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using Npgsql;");
        sb.AppendLine("using NpgsqlTypes;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static partial class {model.ClassName}CRUD");
        sb.AppendLine("    {");

        EmitInsertSql(sb, model);
        sb.AppendLine();
        EmitSelectSql(sb, model);
        sb.AppendLine();
        EmitSelectByIdSql(sb, model);
        sb.AppendLine();
        EmitDeleteSql(sb, model);
        sb.AppendLine();
        EmitBuildInsertParams(sb, model);
        sb.AppendLine();
        EmitReadEntity(sb, model);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitInsertSql(StringBuilder sb, EntityModel model)
    {
        var columns = model.Columns;
        var colNames = string.Join(", ", columns.Select(c => c.ColumnName));
        var paramNames = string.Join(", ", columns.Select(c => "@" + c.ColumnName));
        var sql = $"INSERT INTO {model.TableName} ({colNames}) VALUES ({paramNames});";
        sb.AppendLine($"        public const string InsertSql = \"{Esc(sql)}\";");
    }

    private static void EmitSelectSql(StringBuilder sb, EntityModel model)
    {
        var colNames = string.Join(", ", model.Columns.Select(c => c.ColumnName));
        var sql = $"SELECT {colNames} FROM {model.TableName};";
        sb.AppendLine($"        public const string SelectSql = \"{Esc(sql)}\";");
    }

    private static void EmitSelectByIdSql(StringBuilder sb, EntityModel model)
    {
        var colNames = string.Join(", ", model.Columns.Select(c => c.ColumnName));
        var pk = model.PrimaryKey;
        var pkCol = pk != null ? pk.ColumnName : "id";
        var sql = $"SELECT {colNames} FROM {model.TableName} WHERE {pkCol} = @{pkCol};";
        sb.AppendLine($"        public const string SelectByIdSql = \"{Esc(sql)}\";");
    }

    private static void EmitDeleteSql(StringBuilder sb, EntityModel model)
    {
        var pk = model.PrimaryKey;
        var pkCol = pk != null ? pk.ColumnName : "id";
        var sql = $"DELETE FROM {model.TableName} WHERE {pkCol} = @{pkCol};";
        sb.AppendLine($"        public const string DeleteSql = \"{Esc(sql)}\";");
    }

    private static void EmitBuildInsertParams(StringBuilder sb, EntityModel model)
    {
        sb.AppendLine($"        public static NpgsqlParameter[] BuildInsertParams({model.ClassName} entity)");
        sb.AppendLine("        {");
        sb.AppendLine($"            return new NpgsqlParameter[{model.Columns.Count}]");
        sb.AppendLine("            {");

        for (int i = 0; i < model.Columns.Count; i++)
        {
            var col = model.Columns[i];
            var comma = i < model.Columns.Count - 1 ? "," : "";
            var dbTypePart = GetDbTypeExpression(col);
            var valuePart = GetParamValueExpression(col);
            sb.AppendLine($"                new NpgsqlParameter(\"{col.ColumnName}\", {dbTypePart}) {{ Value = {valuePart} }}{comma}");
        }

        sb.AppendLine("            };");
        sb.AppendLine("        }");
    }

    private static void EmitReadEntity(StringBuilder sb, EntityModel model)
    {
        sb.AppendLine($"        public static {model.ClassName} ReadEntity(NpgsqlDataReader reader)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var entity = new {model.ClassName}();");

        for (int i = 0; i < model.Columns.Count; i++)
        {
            var col = model.Columns[i];
            if (col.IsNullable)
            {
                sb.AppendLine($"            if (!reader.IsDBNull({i}))");
                sb.AppendLine($"                entity.{col.PropertyName} = {GetReaderExpression(col, i)};");
            }
            else
            {
                sb.AppendLine($"            entity.{col.PropertyName} = {GetReaderExpression(col, i)};");
            }
        }

        sb.AppendLine("            return entity;");
        sb.AppendLine("        }");
    }

    private static string GetDbTypeExpression(ColumnModel col)
    {
        var name = col.NpgsqlDbTypeName;
        if (name.Contains("|"))
        {
            // Array type: "Array | NpgsqlDbType.Integer"
            return $"NpgsqlDbType.{name}";
        }
        return $"NpgsqlDbType.{name}";
    }

    private static string GetParamValueExpression(ColumnModel col)
    {
        if (col.IsNullable)
            return $"(object?)entity.{col.PropertyName} ?? DBNull.Value";
        return $"entity.{col.PropertyName}";
    }

    private static string GetReaderExpression(ColumnModel col, int ordinal)
    {
        if (EntityGenerator.NeedsGenericReader(col))
        {
            return $"reader.GetFieldValue<{EntityGenerator.GetClrTypeForCode(col)}>({ordinal})";
        }
        return $"reader.{EntityGenerator.GetReaderMethod(col)}({ordinal})";
    }

    private static string Esc(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
