using System.Text;
using YTStdEntity.Generator.Models;

namespace YTStdEntity.Generator.Emitters;

/// <summary>DAL 代码生成器：生成建表/视图/索引/审计表/触发器代码</summary>
internal static class DalEmitter
{
    /// <summary>生成 {Entity}DAL.g.cs 内容</summary>
    public static string Emit(EntityModel model)
    {
        var sb = new StringBuilder(2048);
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static partial class {model.ClassName}DAL");
        sb.AppendLine("    {");

        // CreateTableSql
        EmitCreateTableSql(sb, model);

        // CreateAuditTableSql
        if (model.NeedAuditTable)
        {
            sb.AppendLine();
            EmitCreateAuditTableSql(sb, model);
        }

        // GetCreateIndexSqls
        sb.AppendLine();
        EmitGetCreateIndexSqls(sb, model);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitCreateTableSql(StringBuilder sb, EntityModel model)
    {
        var ddl = new StringBuilder();
        ddl.Append($"CREATE TABLE IF NOT EXISTS {model.TableName} (");

        for (int i = 0; i < model.Columns.Count; i++)
        {
            var col = model.Columns[i];
            if (i > 0) ddl.Append(", ");
            ddl.Append($"{col.ColumnName} {col.PgType}");

            if (col.IsPrimaryKey)
                ddl.Append(" PRIMARY KEY");
            else if (col.IsRequired || !col.IsNullable)
                ddl.Append(" NOT NULL");
        }

        ddl.Append(")");

        if (model.IsTenantTable)
            ddl.Append(" PARTITION BY LIST (tenant_id)");

        ddl.Append(";");

        sb.AppendLine($"        public const string CreateTableSql = \"{EscapeString(ddl.ToString())}\";");
    }

    private static void EmitCreateAuditTableSql(StringBuilder sb, EntityModel model)
    {
        var auditTableName = model.TableName + "_audit";
        var ddl = new StringBuilder();
        ddl.Append($"CREATE TABLE IF NOT EXISTS {auditTableName} (");
        ddl.Append("audit_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, ");
        ddl.Append("id bigint NOT NULL, ");
        ddl.Append("opt char(1) NOT NULL, ");
        ddl.Append("operated_at TIMESTAMPTZ NOT NULL DEFAULT now(), ");
        ddl.Append("operator_id bigint NOT NULL, ");

        if (model.IsTenantTable)
            ddl.Append("tenant_id int NOT NULL, ");

        ddl.Append("snapshot jsonb NOT NULL");
        ddl.Append(");");

        sb.AppendLine($"        public const string CreateAuditTableSql = \"{EscapeString(ddl.ToString())}\";");
    }

    private static void EmitGetCreateIndexSqls(StringBuilder sb, EntityModel model)
    {
        sb.AppendLine("        public static string[] GetCreateIndexSqls()");
        sb.AppendLine("        {");

        if (model.Indexes.Count == 0)
        {
            sb.AppendLine("            return System.Array.Empty<string>();");
        }
        else
        {
            sb.AppendLine($"            return new string[{model.Indexes.Count}]");
            sb.AppendLine("            {");
            for (int i = 0; i < model.Indexes.Count; i++)
            {
                var idx = model.Indexes[i];
                var unique = idx.IsUnique ? "UNIQUE " : "";
                var columns = string.Join(", ", idx.Columns);
                var sql = $"CREATE {unique}INDEX IF NOT EXISTS {idx.IndexName} ON {model.TableName} ({columns});";
                var comma = i < model.Indexes.Count - 1 ? "," : "";
                sb.AppendLine($"                \"{EscapeString(sql)}\"{comma}");
            }
            sb.AppendLine("            };");
        }

        sb.AppendLine("        }");
    }

    private static string EscapeString(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
